# Generated by Django 5.0.2 on 2024-03-02 05:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.IntegerField(choices=[(1, 'employer'), (2, 'worker')])),
                ('password', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('phone_number', models.IntegerField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'have_done'), (2, 'hevent_done')])),
                ('address', models.CharField(max_length=100)),
                ('created_add', models.DateField(auto_now_add=True)),
                ('start_time', models.DateField(default=datetime.date(2024, 3, 2))),
                ('id_employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employer', to='default.user')),
                ('id_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='default.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.IntegerField(choices=[(1, 'true'), (2, 'False')])),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.service')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='default.user')),
            ],
        ),
    ]
